name = "CB Hugo"
license = "MIT"
licenselink = "https://github.com/clintonbale/cbhugo/blob/master/LICENSE"
description = "A modification of the beautiful hugo theme."
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive"]
features = ["blog", "themes", "disqus", "minimal", "responsive"]
min_version = 0.20

[author]
    name = "clintonbale"
    homepage = "https://clintonbale.com"
    repo = "https://github.com/halogenica/beautifulhugo"

# If Porting existing theme
[original]
    author =  "halogenica"
    homepage = "http://halogenica.net"
    repo = "https://github.com/halogenica/beautifulhugo"
